<?php
namespace grozzzny\catalog;

use Yii;

class CatalogModule extends \yii\easyii\components\Module
{
    public $settings = [
        'modelItem' => '',
        'modelCategory' => '',
        'modelData' => ''
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::registerTranslation();
    }

    public static function registerTranslation()
    {
        Yii::$app->i18n->translations['gr*'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => '@grozzzny/catalog/messages',
        ];
    }
}