<?php
namespace grozzzny\catalog\models;


use Yii;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;

class Properties extends Base
{
    const PRIMARY_MODEL = false;

    const CACHE_KEY = 'gr_catalog_properties';

    const TITLE = 'All properties';
    const SLUG = 'all_properties';

    const SUBMENU_PHOTOS = false;
    const SUBMENU_FILES = false;
    const ORDER_NUM = true;


    const TYPE_STRING = 'string';
    const TYPE_INTEGER = 'integer';
    const TYPE_SELECT = 'select';
    const TYPE_CHECKBOX = 'checkbox';
    const TYPE_HTML = 'html';
    const TYPE_CATEGORY = 'category';
    const TYPE_DATETIME = 'datetime';
    const TYPE_IMAGE = 'image';
    const TYPE_FILE = 'file';


    public static function tableName()
    {
        return 'gr_catalog_properties';
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub

        /**
         * Settings
         */
        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => 'settings',
                ActiveRecord::EVENT_BEFORE_UPDATE => 'settings',
            ],
            'value' => function () {
                return json_encode($this->settings, JSON_UNESCAPED_UNICODE);
            },
        ];

        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_AFTER_INSERT => 'settings',
                ActiveRecord::EVENT_AFTER_UPDATE => 'settings',
                ActiveRecord::EVENT_AFTER_FIND => 'settings',
            ],
            'value' => function () {
                return json_decode($this->settings);
            },
        ];


        /**
         * validation_rule
         */
        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => 'validation_rule',
                ActiveRecord::EVENT_BEFORE_UPDATE => 'validation_rule',
            ],
            'value' => function () {
                return json_encode($this->validation_rule, JSON_UNESCAPED_UNICODE);
            },
        ];

        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_AFTER_INSERT => 'validation_rule',
                ActiveRecord::EVENT_AFTER_UPDATE => 'validation_rule',
                ActiveRecord::EVENT_AFTER_FIND => 'validation_rule',
            ],
            'value' => function () {
                return json_decode($this->validation_rule, true);
            },
        ];


        /**
         * Options
         */
        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => 'options',
                ActiveRecord::EVENT_BEFORE_UPDATE => 'options',
            ],
            'value' => function () {
                return json_encode($this->options, JSON_UNESCAPED_UNICODE);
            },
        ];

        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_AFTER_INSERT => 'options',
                ActiveRecord::EVENT_AFTER_UPDATE => 'options',
                ActiveRecord::EVENT_AFTER_FIND => 'options',
            ],
            'value' => function () {
                return json_decode($this->options);
            },
        ];

        return $behaviors;
    }



    public function rules()
    {
        return [
            ['id', 'number', 'integerOnly' => true],
            ['slug', 'match', 'pattern' => '/^[\w\-]+$/'],
            ['slug', 'unique'],
            [[
                'title',
                'type',
            ], 'string'],
            [[
                'order_num',
            ], 'integer'],
            [['settings','validation_rule','options'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gr', 'ID'),
            'slug' => Yii::t('gr', 'Slug'),
            'title' => Yii::t('gr', 'Title'),
            'type' => Yii::t('gr', 'Type'),
            'settings' => Yii::t('gr', 'Settings'),
            'validation_rule' => Yii::t('gr', 'Validation Rule'),
            'order_num' => Yii::t('gr', 'Sort Index'),
        ];
    }

    public static function getListType()
    {
        return [
            self::TYPE_STRING => Yii::t('gr','String'),
            self::TYPE_INTEGER => Yii::t('gr','Integer'),
            self::TYPE_SELECT => Yii::t('gr','Select'),
            self::TYPE_CHECKBOX => Yii::t('gr','Checkbox'),
            self::TYPE_HTML => Yii::t('gr','HTML'),
            self::TYPE_CATEGORY => Yii::t('gr','Category'),
            self::TYPE_DATETIME => Yii::t('gr','Datetime'),
            self::TYPE_IMAGE => Yii::t('gr','Image'),
            self::TYPE_FILE => Yii::t('gr','File'),
        ];
    }

    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'])
            ->viaTable('gr_catalog_relations_categories_properties', ['item_id' => 'id']);
    }

    /**
     * Only type "TYPE_CATEGORY"
     * @return null|\yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return ($this->type == self::TYPE_CATEGORY) ? $this->hasOne(Category::className(), ['id' => $this->options->category_id]) : null;
    }


    public function getValidationsJson()
    {
        return (empty($this->validation_rule)) ? '{}' : json_encode($this->validation_rule, JSON_UNESCAPED_UNICODE);
    }

    public function getOptionsJson()
    {
        return (empty($this->options)) ? '{}' : json_encode($this->options, JSON_UNESCAPED_UNICODE);
    }

    public function getSettingsJson()
    {
        return (empty($this->settings)) ? '{}' : json_encode($this->settings, JSON_UNESCAPED_UNICODE);
    }
}
