<?php
namespace grozzzny\catalog\models;


use Yii;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

class Properties extends Base
{
    const PRIMARY_MODEL = false;

    const CACHE_KEY = 'gr_catalog_properties';

    const TITLE = 'All properties';
    const SLUG = 'all_properties';

    const SUBMENU_PHOTOS = false;
    const SUBMENU_FILES = false;
    const ORDER_NUM = true;


    const TYPE_STRING = 'string';
    const TYPE_INTEGER = 'integer';
    const TYPE_SELECT = 'select';
    const TYPE_CHECKBOX = 'checkbox';
    const TYPE_HTML = 'html';
    const TYPE_CATEGORY = 'category';
    const TYPE_MULTICATEGORY = 'multicategory';
    const TYPE_ITEMSCATEGORY = 'itemscategory';
    const TYPE_DATETIME = 'datetime';
    const TYPE_IMAGE = 'image';
    const TYPE_FILE = 'file';
    const TYPE_CODE = 'code';

    public $category_id = null;

    public static function tableName()
    {
        return 'gr_catalog_properties';
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub

        /**
         * Settings
         */
        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => 'settings',
                ActiveRecord::EVENT_BEFORE_UPDATE => 'settings',
            ],
            'value' => function () {
                return json_encode($this->settings, JSON_UNESCAPED_UNICODE);
            },
        ];

        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_AFTER_INSERT => 'settings',
                ActiveRecord::EVENT_AFTER_UPDATE => 'settings',
                ActiveRecord::EVENT_AFTER_FIND => 'settings',
            ],
            'value' => function () {
                return json_decode($this->settings);
            },
        ];


        /**
         * validations
         */
        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => 'validations',
                ActiveRecord::EVENT_BEFORE_UPDATE => 'validations',
            ],
            'value' => function () {
                return json_encode($this->validations, JSON_UNESCAPED_UNICODE);
            },
        ];

        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_AFTER_INSERT => 'validations',
                ActiveRecord::EVENT_AFTER_UPDATE => 'validations',
                ActiveRecord::EVENT_AFTER_FIND => 'validations',
            ],
            'value' => function () {
                return json_decode($this->validations, true);
            },
        ];


        /**
         * Options
         */
        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => 'options',
                ActiveRecord::EVENT_BEFORE_UPDATE => 'options',
            ],
            'value' => function () {
                return json_encode($this->options, JSON_UNESCAPED_UNICODE);
            },
        ];

        $behaviors[] = [
            'class' => AttributeBehavior::class,
            'attributes' => [
                ActiveRecord::EVENT_AFTER_INSERT => 'options',
                ActiveRecord::EVENT_AFTER_UPDATE => 'options',
                ActiveRecord::EVENT_AFTER_FIND => 'options',
            ],
            'value' => function () {
                return json_decode($this->options);
            },
        ];

        return $behaviors;
    }

    public function rules()
    {
        return [
            ['id', 'number', 'integerOnly' => true],
            ['slug', 'match', 'pattern' => '/^[\w\-]+$/'],
            ['slug', 'unique'],
            [[
                'title',
                'type',
            ], 'string'],
            [[
                'category_id',
                'order_num',
                'index',
            ], 'integer'],
            [['settings','validations','options'], 'safe'],
            ['category_id', 'required']
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gr', 'ID'),
            'slug' => Yii::t('gr', 'Slug'),
            'title' => Yii::t('gr', 'Title'),
            'type' => Yii::t('gr', 'Type'),
            'settings' => Yii::t('gr', 'Settings'),
            'validations' => Yii::t('gr', 'Validation Rule'),
            'order_num' => Yii::t('gr', 'Sort Index'),
            'index' => Yii::t('gr', 'Index'),
        ];
    }


    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if (!$this->getCategories()->where(['id' => $this->category_id])->exists()){
            Category::findOne($this->category_id)->link('properties', $this);
        }
    }

    public static function getListType()
    {
        return [
            self::TYPE_STRING => Yii::t('gr','String'),
            self::TYPE_INTEGER => Yii::t('gr','Integer'),
            self::TYPE_SELECT => Yii::t('gr','Select'),
            self::TYPE_CHECKBOX => Yii::t('gr','Checkbox'),
            self::TYPE_HTML => Yii::t('gr','HTML'),
            self::TYPE_CATEGORY => Yii::t('gr','Category'),
            self::TYPE_MULTICATEGORY => Yii::t('gr','Multi category'),
            self::TYPE_ITEMSCATEGORY => Yii::t('gr','Items category'),
            self::TYPE_DATETIME => Yii::t('gr','Datetime'),
            self::TYPE_IMAGE => Yii::t('gr','Image'),
            self::TYPE_FILE => Yii::t('gr','File'),
            self::TYPE_CODE => Yii::t('gr','Code'),
        ];
    }

    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'])
            ->viaTable('gr_catalog_relations_categories_properties', ['property_id' => 'id']);
    }

    /**
     * Only type "TYPE_CATEGORY"
     * @return null|\yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return ($this->type == self::TYPE_CATEGORY) ? $this->hasOne(Category::className(), ['id' => $this->options->category_id]) : null;
    }


    public function getValidationsJson()
    {
        return (empty($this->validations)) ? '{}' : json_encode($this->validations, JSON_UNESCAPED_UNICODE);
    }

    public function getOptionsJson()
    {
        return (empty($this->options)) ? '{}' : json_encode($this->options, JSON_UNESCAPED_UNICODE);
    }

    public function getSettingsJson()
    {
        return (empty($this->settings)) ? '{}' : json_encode($this->settings, JSON_UNESCAPED_UNICODE);
    }
}
